import { DM_Sans, DM_Serif_Text  } from 'next/font/google';
import "./globals.css";
import Header from './headercomponents/Header';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weights: [400, 500, 700],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "YAYYU LAGOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <Header/>
        {children}
      
      </body>
    </html>
  );
}
